# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from qa.v1 import qa_pb2 as qa_dot_v1_dot_qa__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in qa/v1/qa_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/qa.v1.CoreService/Health',
                request_serializer=qa_dot_v1_dot_qa__pb2.Empty.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.HealthReply.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/qa.v1.CoreService/Register',
                request_serializer=qa_dot_v1_dot_qa__pb2.RegisterRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.AuthReply.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/qa.v1.CoreService/Login',
                request_serializer=qa_dot_v1_dot_qa__pb2.LoginRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.AuthReply.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/qa.v1.CoreService/Logout',
                request_serializer=qa_dot_v1_dot_qa__pb2.LogoutRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.Empty.FromString,
                _registered_method=True)
        self.Me = channel.unary_unary(
                '/qa.v1.CoreService/Me',
                request_serializer=qa_dot_v1_dot_qa__pb2.MeRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.AuthReply.FromString,
                _registered_method=True)
        self.UploadDocument = channel.unary_unary(
                '/qa.v1.CoreService/UploadDocument',
                request_serializer=qa_dot_v1_dot_qa__pb2.UploadDocumentRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.DocumentReply.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/qa.v1.CoreService/ListDocuments',
                request_serializer=qa_dot_v1_dot_qa__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.ListDocumentsReply.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/qa.v1.CoreService/GetDocument',
                request_serializer=qa_dot_v1_dot_qa__pb2.DocumentRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.DocumentReply.FromString,
                _registered_method=True)
        self.DownloadDocument = channel.unary_unary(
                '/qa.v1.CoreService/DownloadDocument',
                request_serializer=qa_dot_v1_dot_qa__pb2.DocumentRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.DownloadDocumentReply.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/qa.v1.CoreService/DeleteDocument',
                request_serializer=qa_dot_v1_dot_qa__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.Empty.FromString,
                _registered_method=True)
        self.ListThreads = channel.unary_unary(
                '/qa.v1.CoreService/ListThreads',
                request_serializer=qa_dot_v1_dot_qa__pb2.ListThreadsRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.ListThreadsReply.FromString,
                _registered_method=True)
        self.CreateThread = channel.unary_unary(
                '/qa.v1.CoreService/CreateThread',
                request_serializer=qa_dot_v1_dot_qa__pb2.CreateThreadRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.ThreadReply.FromString,
                _registered_method=True)
        self.CreateTurn = channel.unary_unary(
                '/qa.v1.CoreService/CreateTurn',
                request_serializer=qa_dot_v1_dot_qa__pb2.CreateTurnRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.CreateTurnReply.FromString,
                _registered_method=True)
        self.CreateTurnStream = channel.unary_stream(
                '/qa.v1.CoreService/CreateTurnStream',
                request_serializer=qa_dot_v1_dot_qa__pb2.CreateTurnRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.TurnItem.FromString,
                _registered_method=True)
        self.ListTurns = channel.unary_unary(
                '/qa.v1.CoreService/ListTurns',
                request_serializer=qa_dot_v1_dot_qa__pb2.ListTurnsRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.ListTurnsReply.FromString,
                _registered_method=True)
        self.GetTurn = channel.unary_unary(
                '/qa.v1.CoreService/GetTurn',
                request_serializer=qa_dot_v1_dot_qa__pb2.GetTurnRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.GetTurnReply.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/qa.v1.CoreService/GetConfig',
                request_serializer=qa_dot_v1_dot_qa__pb2.MeRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.ConfigReply.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/qa.v1.CoreService/SetConfig',
                request_serializer=qa_dot_v1_dot_qa__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.ConfigReply.FromString,
                _registered_method=True)


class CoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Me(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListThreads(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTurnStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTurns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.Empty.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.HealthReply.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.RegisterRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.AuthReply.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.LoginRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.AuthReply.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.LogoutRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.Empty.SerializeToString,
            ),
            'Me': grpc.unary_unary_rpc_method_handler(
                    servicer.Me,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.MeRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.AuthReply.SerializeToString,
            ),
            'UploadDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDocument,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.UploadDocumentRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.DocumentReply.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.ListDocumentsRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.ListDocumentsReply.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.DocumentRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.DocumentReply.SerializeToString,
            ),
            'DownloadDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadDocument,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.DocumentRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.DownloadDocumentReply.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.Empty.SerializeToString,
            ),
            'ListThreads': grpc.unary_unary_rpc_method_handler(
                    servicer.ListThreads,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.ListThreadsRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.ListThreadsReply.SerializeToString,
            ),
            'CreateThread': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateThread,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.CreateThreadRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.ThreadReply.SerializeToString,
            ),
            'CreateTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTurn,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.CreateTurnRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.CreateTurnReply.SerializeToString,
            ),
            'CreateTurnStream': grpc.unary_stream_rpc_method_handler(
                    servicer.CreateTurnStream,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.CreateTurnRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.TurnItem.SerializeToString,
            ),
            'ListTurns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTurns,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.ListTurnsRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.ListTurnsReply.SerializeToString,
            ),
            'GetTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTurn,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.GetTurnRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.GetTurnReply.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.MeRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.ConfigReply.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.SetConfigRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.ConfigReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qa.v1.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qa.v1.CoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/Health',
            qa_dot_v1_dot_qa__pb2.Empty.SerializeToString,
            qa_dot_v1_dot_qa__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/Register',
            qa_dot_v1_dot_qa__pb2.RegisterRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.AuthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/Login',
            qa_dot_v1_dot_qa__pb2.LoginRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.AuthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/Logout',
            qa_dot_v1_dot_qa__pb2.LogoutRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Me(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/Me',
            qa_dot_v1_dot_qa__pb2.MeRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.AuthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/UploadDocument',
            qa_dot_v1_dot_qa__pb2.UploadDocumentRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.DocumentReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/ListDocuments',
            qa_dot_v1_dot_qa__pb2.ListDocumentsRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.ListDocumentsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/GetDocument',
            qa_dot_v1_dot_qa__pb2.DocumentRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.DocumentReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/DownloadDocument',
            qa_dot_v1_dot_qa__pb2.DocumentRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.DownloadDocumentReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/DeleteDocument',
            qa_dot_v1_dot_qa__pb2.DeleteDocumentRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListThreads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/ListThreads',
            qa_dot_v1_dot_qa__pb2.ListThreadsRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.ListThreadsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/CreateThread',
            qa_dot_v1_dot_qa__pb2.CreateThreadRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.ThreadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/CreateTurn',
            qa_dot_v1_dot_qa__pb2.CreateTurnRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.CreateTurnReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTurnStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/qa.v1.CoreService/CreateTurnStream',
            qa_dot_v1_dot_qa__pb2.CreateTurnRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.TurnItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTurns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/ListTurns',
            qa_dot_v1_dot_qa__pb2.ListTurnsRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.ListTurnsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/GetTurn',
            qa_dot_v1_dot_qa__pb2.GetTurnRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.GetTurnReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/GetConfig',
            qa_dot_v1_dot_qa__pb2.MeRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.ConfigReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.CoreService/SetConfig',
            qa_dot_v1_dot_qa__pb2.SetConfigRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.ConfigReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LlmServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/qa.v1.LlmService/Health',
                request_serializer=qa_dot_v1_dot_qa__pb2.Empty.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.HealthReply.FromString,
                _registered_method=True)
        self.EmbedTexts = channel.unary_unary(
                '/qa.v1.LlmService/EmbedTexts',
                request_serializer=qa_dot_v1_dot_qa__pb2.EmbedTextsRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.EmbedTextsReply.FromString,
                _registered_method=True)
        self.ExtractDocumentText = channel.unary_unary(
                '/qa.v1.LlmService/ExtractDocumentText',
                request_serializer=qa_dot_v1_dot_qa__pb2.ExtractDocumentTextRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.ExtractDocumentTextReply.FromString,
                _registered_method=True)
        self.GenerateAnswer = channel.unary_unary(
                '/qa.v1.LlmService/GenerateAnswer',
                request_serializer=qa_dot_v1_dot_qa__pb2.GenerateAnswerRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.GenerateAnswerReply.FromString,
                _registered_method=True)
        self.StreamGenerateAnswer = channel.unary_stream(
                '/qa.v1.LlmService/StreamGenerateAnswer',
                request_serializer=qa_dot_v1_dot_qa__pb2.GenerateAnswerRequest.SerializeToString,
                response_deserializer=qa_dot_v1_dot_qa__pb2.GenerateAnswerChunk.FromString,
                _registered_method=True)


class LlmServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedTexts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractDocumentText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGenerateAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.Empty.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.HealthReply.SerializeToString,
            ),
            'EmbedTexts': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedTexts,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.EmbedTextsRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.EmbedTextsReply.SerializeToString,
            ),
            'ExtractDocumentText': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractDocumentText,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.ExtractDocumentTextRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.ExtractDocumentTextReply.SerializeToString,
            ),
            'GenerateAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAnswer,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.GenerateAnswerRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.GenerateAnswerReply.SerializeToString,
            ),
            'StreamGenerateAnswer': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGenerateAnswer,
                    request_deserializer=qa_dot_v1_dot_qa__pb2.GenerateAnswerRequest.FromString,
                    response_serializer=qa_dot_v1_dot_qa__pb2.GenerateAnswerChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qa.v1.LlmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qa.v1.LlmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LlmService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.LlmService/Health',
            qa_dot_v1_dot_qa__pb2.Empty.SerializeToString,
            qa_dot_v1_dot_qa__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedTexts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.LlmService/EmbedTexts',
            qa_dot_v1_dot_qa__pb2.EmbedTextsRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.EmbedTextsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractDocumentText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.LlmService/ExtractDocumentText',
            qa_dot_v1_dot_qa__pb2.ExtractDocumentTextRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.ExtractDocumentTextReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.v1.LlmService/GenerateAnswer',
            qa_dot_v1_dot_qa__pb2.GenerateAnswerRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.GenerateAnswerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGenerateAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/qa.v1.LlmService/StreamGenerateAnswer',
            qa_dot_v1_dot_qa__pb2.GenerateAnswerRequest.SerializeToString,
            qa_dot_v1_dot_qa__pb2.GenerateAnswerChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
